<?php

namespace Generators\Filament3\Modules;

use App\Enums\CrudFieldTypes;
use App\Enums\CrudTypes;
use App\Interfaces\ModuleBase;
use App\Models\Crud;
use App\Models\CrudField;
use App\Models\CrudFieldOptions;

class ClientManagementModule extends ModuleBase
{
    public string $slug = 'client-management';

    public function getCruds(): array
    {
        return [
            (new Crud([
                'type' => CrudTypes::PARENT,
                'title' => str('Client Management Settings')->singular()->studly(),
                'visual_title' => 'Client Management Settings',
                'icon' => 'heroicon-o-cog-8-tooth',
                'menu_order' => 2,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ])),
            (new Crud([
                'parent_id' => str('Client Management Settings')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'Currency',
                'visual_title' => 'Currencies',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => str('Name')->lower()
                            ->snake()
                            ->toString(),
                        'label' => 'Name',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'code',
                        'label' => 'Currency Code',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::CHECKBOX,
                        'key' => 'main_currency',
                        'label' => 'Main currency',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management Settings')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'TransactionType',
                'visual_title' => 'Transaction Types',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => str('Name')->lower()
                            ->snake()
                            ->toString(),
                        'label' => 'Name',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management Settings')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'IncomeSource',
                'visual_title' => 'Income Sources',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => str('Name')->lower()
                            ->snake()
                            ->toString(),
                        'label' => 'Name',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::FLOAT,
                        'key' => 'fee_percent',
                        'label' => 'Fee Percent',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management Settings')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'ClientStatus',
                'visual_title' => 'Client Status',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => str('Name')->lower()
                            ->snake()
                            ->toString(),
                        'label' => 'Name',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management Settings')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'ProjectStatus',
                'visual_title' => 'Project Status',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => str('Name')->lower()
                            ->snake()
                            ->toString(),
                        'label' => 'Name',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            // Client Management
            (new Crud([
                'type' => CrudTypes::PARENT,
                'title' => str('Client Management')->singular()->studly(),
                'visual_title' => 'Client Management',
                'icon' => 'heroicon-o-briefcase',
                'menu_order' => 2,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ])),

            (new Crud([
                'parent_id' => str('Client Management')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'Client',
                'visual_title' => 'Clients',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'first_name',
                        'label' => 'First Name',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'last_name',
                        'label' => 'Last Name',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'company',
                        'label' => 'Company',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::EMAIL,
                        'key' => 'email',
                        'label' => 'Email',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'phone',
                        'label' => 'Phone',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'website',
                        'label' => 'Website',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'skype',
                        'label' => 'Skype',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'country',
                        'label' => 'Country',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'status',
                        'label' => 'Status',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'ClientStatus',
                            'related_crud_field_id' => 'name',
                        ])),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'Project',
                'visual_title' => 'Projects',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'name',
                        'label' => 'Name',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'client',
                        'label' => 'Client',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'Client',
                            'related_crud_field_id' => 'first_name',
                        ])),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXTAREA,
                        'key' => 'description',
                        'label' => 'Description',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::DATE,
                        'key' => 'start_date',
                        'label' => 'Start Date',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::MONEY,
                        'key' => 'budget',
                        'label' => 'Budget',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'status',
                        'label' => 'Status',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'ProjectStatus',
                            'related_crud_field_id' => 'name',
                        ])),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'Note',
                'visual_title' => 'Notes',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'project',
                        'label' => 'Project',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'Project',
                            'related_crud_field_id' => 'name',
                        ])),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXTAREA,
                        'key' => 'note_text',
                        'label' => 'Notes',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'Document',
                'visual_title' => 'Documents',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'project',
                        'label' => 'Project',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'Project',
                            'related_crud_field_id' => 'name',
                        ])),
                    new CrudField([
                        'type' => CrudFieldTypes::FILE,
                        'key' => 'document_file',
                        'label' => 'File',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'name',
                        'label' => 'Name',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXTAREA,
                        'key' => 'description',
                        'label' => 'Description',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
            (new Crud([
                'parent_id' => str('Client Management')->singular()->studly(),
                'type' => CrudTypes::CRUD,
                'title' => 'Transaction',
                'visual_title' => 'Transactions',
                'icon' => '',
                'menu_order' => 1,
                'is_hidden' => false,
                'module_crud' => true,
                'module_slug' => $this->slug,
                'system' => true,
            ]))
                ->setRelation('fields', [
                    $this->getIDField(),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'project',
                        'label' => 'Project',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'Project',
                            'related_crud_field_id' => 'name',
                        ])),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'transaction_type',
                        'label' => 'Transaction Type',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'TransactionType',
                            'related_crud_field_id' => 'name',
                        ])),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'income_source',
                        'label' => 'Income Source',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'IncomeSource',
                            'related_crud_field_id' => 'name',
                        ])),
                    new CrudField([
                        'type' => CrudFieldTypes::MONEY,
                        'key' => 'amount',
                        'label' => 'Amount',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    (new CrudField([
                        'type' => CrudFieldTypes::BELONGS_TO,
                        'key' => 'currency',
                        'label' => 'Currency',
                        'validation' => 'required',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]))
                        ->setRelation('crudFieldOptions', new CrudFieldOptions([
                            'crud_id' => 'Currency',
                            'related_crud_field_id' => 'name',
                        ])),
                    new CrudField([
                        'type' => CrudFieldTypes::DATE,
                        'key' => 'transaction_date',
                        'label' => 'Transaction Date',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXT,
                        'key' => 'name',
                        'label' => 'Name',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    new CrudField([
                        'type' => CrudFieldTypes::TEXTAREA,
                        'key' => 'description',
                        'label' => 'Description',
                        'validation' => 'optional',
                        'in_list' => true,
                        'in_show' => true,
                        'in_create' => true,
                        'in_edit' => true,
                        'nullable' => false,
                        'tooltip' => null,
                        'system' => true,
                        'enabled' => true,
                        'order' => 2,
                    ]),
                    $this->getCreatedAtField(3),
                    $this->getUpdatedAtField(4),
                    $this->getDeletedAtField(5),
                ]
                ),
        ];
    }
}
